packages:
  - ASafariM.Api
  - ASafariM.Clients/asafarim-ui
  - ASafariM.Clients/asafarim-blog
  - ASafariM.Clients/asafarim-bibliography
  - ASafariM.Clients/asafarim-pbk
  - ASafariM.Clients/asafarim-cli
