import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-publications',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './publications.component.html',
  styleUrls: ['./publications.component.scss']
})
export class PublicationsComponent {
  pageTitle = 'Research Publications';

  publications = [
    {
      title: 'WetSpa model application in the Distributed Model Intercomparison Project (DMIP2)',
      authors: 'Michael B. Smith, Alireza Safari, Florimond De Smedt, Fekadu Moreda, Mohsen Tavakoli, ...',
      journal: 'Journal of Hydrology',
      year: 2012,
      publisher: 'Elsevier',
      volume: '418-419',
      issue: undefined,
      pages: '78-89',
      doi: 'https://doi.org/10.1016/j.jhydrol.2009.04.001',
      downloadUrl: 'https://www.researchgate.net/profile/Alireza-Safari-3/publication/229115485_WetSpa_Model_Application_in_the_Distributed_Model_Intercomparison_Project_DMIP2/links/5df95117a6fdcc283728dc97/WetSpa-Model-Application-in-the-Distributed-Model-Intercomparison-Project-DMIP2.pdf',
      abstract: 'This paper describes the application of a spatially distributed hydrologic model (WetSpa) Water and Energy Transfer between Soil, Plants and Atmosphere, for the second phase of the Distributed Model Intercomparison Project (DMIP2) study. The model implementation is based on 30-m spatial resolution and 1 h time-step for all basins and interior watersheds involved in the DMIP study. Rainfall inputs are derived from Next Generation Radar (NEXRAD). The distributed model parameters are based on an extensive database of watershed characteristics available for the region, including digital maps of topography, soil type, and landuse. The model is calibrated and validated on part of the river flow records for each basin and applied to the smaller interior watersheds not used in calibration to assess the model performance in ungaged basins. The statistics improve significantly with calibration of the global model parameters but even for uncalibrated simulations, the WetSpa model reproduces flow rates of acceptable accuracy for most cases. To evaluate the model performance during calibration and validation periods, an Aggregated Measure (AM) is introduced that measures different aspects of the simulated hydrograph such as shape, size and volume. The statistics for the five calibration basins show that the model produces very good to excellent results for the calibration period. With the exception of Blue River basin, the overall model performance for the validation period remains good to very good, indicating that the model is able to simulate the relevant hydrologic processes in the basins accurately. The performance of the uncalibrated model for the subcatchments is more variable, but the hourly flow rates generally reproduced with reasonable accuracy indicating an encouraging performance of the model.',
      citations: 110
    }, {
      title: 'Results of the DMIP 2 Oklahoma experiments',
      authors: 'Alireza Safari, Florimond De Smedt, Mohsen Tavakoli, Fekadu Moreda',
      journal: 'Journal of Hydrology',
      year: 2012,
      publisher: 'Elsevier',
      volume: '418-419',
      issue: undefined,
      pages: '17-48',
      doi: 'https://doi.org/10.1016/j.jhydrol.2011.08.056',
      downloadUrl: 'https://www.sciencedirect.com/science/article/abs/pii/S0022169411006123',
      abstract: 'Phase 2 of the Distributed Model Intercomparison Project (DMIP 2) was formulated primarily as a mechanism to help guide the US National Weather Service (NWS) as it expands its use of spatially distributed watershed models for operational river, flash flood, and water resources forecasting. The overall purpose of DMIP 2 was to test many distributed models with operational quality data with a view towards meeting NWS operational forecasting needs. At the same time, DMIP 2 was formulated as an experiment that could be leveraged by the broader scientific community as a platform for testing, evaluating, and improving the science of spatially distributed models. This paper presents the key results of the DMIP 2 experiments conducted for the Oklahoma region, which included comparison of lumped and distributed model simulations generated with uncalibrated and calibrated parameters, water balance tests, routing and soil moisture tests, and simulations at interior locations. Simulations from 14 independent groups and 16 models are analyzed. As in DMIP 1, the participant simulations were evaluated against observed hourly streamflow data and compared with simulations generated by the NWS operational lumped model. A wide range of statistical measures are used to evaluate model performance on both run-period and event basis. A noteworthy improvement in DMIP 2 was the combined use of two lumped models to form the benchmark for event improvement statistics, where improvement was measured in terms of runoff volume, peak flow, and peak timing for between 20 and 40 events in each basin. Results indicate that in general, those spatially distributed models that are calibrated to perform well for basin outlet simulations also, in general, perform well at interior points whose drainage areas cover a wide range of scales. Two of the models were able to provide reasonable estimates of soil moisture versus depth over a wide geographic domain and through a period containing two severe droughts. In several parent and interior basins, a few uncalibrated spatially distributed models were able to achieve better goodness-of-fit statistics than other calibrated distributed models, highlighting the strength of those model structures combined with their a priori parameters. In general, calibration solely at basin outlets alone was not able to greatly improve relative model performance beyond that established by using uncalibrated a priori parameters. Further, results from the experiment for returning DMIP 1 participants reinforce the need for stationary data for model calibration: in some cases, the improvements gained by distributed models compared to lumped were not realized when the models were calibrated using inconsistent precipitation data from DMIP 1. Event-average improvement of distributed models over the combined lumped benchmark was measured in terms of runoff volume, peak flow, and peak timing for between 20 and 40 events. The percentage of model-basin pairs having positive distributed model improvement at basin outlets and interior points was 18%, 24%, and 28% respectively, for these quantities. These values correspond to 14%, 33%, and 22% respectively, in DMIP 1. While there may not seem to be much gain compared to DMIP 1 results, the DMIP 2 values were based on more precipitation–runoff events, more model-basin combinations (148 versus 51), more interior ungauged points (9 versus 3), and a benchmark comprised of two lumped model simulations. In addition, we propose a set of statistical measures that can be used to guide the calibration of distributed and lumped models for operational forecasting.',
      citations: 109
    },
    {
      title: 'Improving the Confidence in Hydrologic Model Calibration and Prediction by Transformation of Model Residuals',
      authors: 'Alireza Safari, Florimond De Smedt',
      journal: 'Journal of Hydrologic Engineering',
      publisher: 'American Society of Civil Engineers (ASCE)',
      year: 2015,
      volume: '20',
      issue: '9',
      pages: '12',
      doi: 'https://doi.org/10.1007/s11269-017-1765-8',
      abstract: 'Calibration of a distributed hydrologic model (WetSpa) for modeling river flows is performed using automatic parameter optimization. The main purpose of this research is to provide more confidence in the uncertainty analysis of the model parameters and predictions. A Box-Cox transformation and an autoregressive integrated moving average (ARIMA) time series model are used to transform the correlated and nonstationary model residuals to white noise disturbances, which can be minimized by ordinary least squares optimization. The WetSpa model is applied to the Illinois River basin, with a spatial resolution of 30 m and 1 h time step for a 10-year simulation period (1996–2006). The model is calibrated using river flow records (1996–2002) and validated using the remaining flow data (2002–2006). The results show that simple calibration of the model is inaccurate, as the residuals exhibit heteroscedasticity, which results in inaccurate estimates of the model parameters and large prediction uncertainty. The model calibration is improved when the calibration is combined with a Box-Cox transformation of the discharge and ARIMA modeling of the residuals, which considerably enhances the confidence of the model parameter estimates and of the model predictions.',
      citations: 8
    },
    {
      title: 'Improving WetSpa model to predict streamflows for gaged and ungaged catchments',
      authors: 'Alireza Safari, Florimond De Smedt',
      journal: 'Journal of Hydroinformatics',
      year: 2014,
      volume: '16',
      issue: '4',
      pages: '758-771',
      doi: 'https://doi.org/10.2166/hydro.2013.216',
      abstract: 'In the second phase of the Distributed Model Intercomparison Project (DMIP2), the WetSpa model is applied to simulate flows at basin and subbasin scales. Parent basins and their nested subbasins are modeled as gaged and ungaged basins, respectively. Available observations in the subbasins were only used to validate the model predictions. Gaged basins simulation results show that the predictions and observations are in good agreement. However, major peaks are underestimated, as is often the case in runoff modeling. Underestimation of high flows and in particular peak flows indicates that the prediction of actual runoff coefficients in the current WetSpa model needs to be improved. Also, sensitivity analysis of the model parameters reveals that the baseflow recession coefficient is the most sensitive parameter and care should be taken when modeling ungaged basins. Hence, by estimating this parameter for each subbasin separately, the model performance for the subbasins can be improved. To do this, a Boussinesq groundwater flow equation is used to improve the prediction of baseflow recession coefficients in the subbasins. Comparison between the original and the modified WetSpa models shows that the modified model yields relatively higher performances for the subbasins, creating a more accurate model for predicting ungaged subbasins.',
      citations: 4
    },
    {
      title: 'Stream Flow Simulation using Radar-based Precipitation Applied to the Illinois River Basin in Oklahoma, USA',
      authors: 'Alireza Safari, F De Smedt',
      publisher: 'Water Observation & Information System for Balkan',
      conference: 'BALWOIS Conference',
      year: 2008,
      volume: '73',
      pages: '16',
      downloadUrl: 'https://www.researchgate.net/profile/Alireza-Safari-3/publication/228902741_Stream_Flow_Simulation_using_Radar-based_Precipitation_Applied_to_the_Illinois_River_Basin_in_Oklahoma_USA/links/0a85e530f02c07fad2000000/Stream-Flow-Simulation-using-Radar-based-Precipitation-Applied-to-the-Illinois-River-Basin-in-Oklahoma-USA.pdf',
      abstract: 'This paper describes the application of a spatially distributed hydrological model WetSpa (Water and Energy Transfer between Soil, Plants and Atmosphere) using radar-based rainfall data provide by the United States Hydrology Laboratory of NOAA’s National Weather Service for a distributed model intercomparison project. The model is applied to the river basin above Tahlequah hydrometry station with 30-m spatial resolution and one hour time–step for a total simulation period of 6 years. Rainfall inputs are derived from radar. The distributed model parameters are based on an extensive database of watershed characteristics available for the region, including digital maps of DEM, soil type, and land use. The model is calibrated and validated on part of the river flow records. The simulated hydrograph shows a good correspondence with observation (Nash efficiency coeffiecient> 80%, indicating that the model is able to simulate the relevant hydrologic processes in the basin accurately.',
      citations: 6
    },
    {
      title: 'Study and development of a distributed Hydrologic Model,WetSpa, applied to the DMIP2 basins in Oklahoma USA',
      authors: 'Alireza Safari',
      publisher: 'Vrije Universiteit Brussel',
      source: 'PhD thesis',
      year: 2012,
      volume: '1',
      pages: '182',
      downloadUrl: 'https://www.researchgate.net/profile/Alireza-Safari-3/publication/228902741_Stream_Flow_Simulation_using_Radar-based_Precipitation_Applied_to_the_Illinois_River_Basin_in_Oklahoma_USA/links/0a85e530f02c07fad2000000/Stream-Flow-Simulation-using-Radar-based-Precipitation-Applied-to-the-Illinois-River-Basin-in-Oklahoma-USA.pdf',
      abstract: 'Hydrological models are developed to better understand hydrological processes by easing the characterization of the real world data. Distributed hydrological models are used and developed to model spatially distributed hydrological processes in an entire catchment. Dealing with spatial distribution of parameters makes such models capable of performing various water resource assessments based on current and future changes in catchments, as well as for flood prediction. The WetSpa distributed hydrologic model is used to assess how well distributed models can reproduce streamflow, and generate meaningful hydrographs at interior locations or ungaged-basins. This is done by applying the WetSpa model to the second phase of the" Distributed Model Intercomparison Project", or DMIP2, organized by the National Oceanic and Atmospheric Administration (NOAA), National Weather Service-Office of Hydrologic Development (NWS-OHD), USA. Data from 17 United States Geological Survey streamflow gaging stations are used in this study. The model implementations are based on 30-m spatial resolution and 1 hour time-step for all basins. There are five parent basins with nested subbasins. Two types of simulations are performed, ie simulations with uncalibrated model parameters and simulations with optimized model parameters. In order to estimate the model parameters, while reducing the model calibration effort, an automated calibration procedure is applied by incorporating a model-independent.',
      citations: 2
    }
  ];

  categories = [
    { name: 'Hydrological Modeling', count: 4 },
    { name: 'Uncertainty Analysis', count: 1 },
    { name: 'Data Science', count: 2 },
    { name: 'Remote Sensing', count: 1 },
    { name: 'Algorithmic Approaches', count: 4 }
  ];

  selectedCategory: string | null = null;

  citationStats = {
    total: 239,
    hIndex: 4,
    i10Index: 2,
    yearlyStats: [
      { year: 2018, count: 25 },
      { year: 2019, count: 21 },
      { year: 2020, count: 13 },
      { year: 2021, count: 12 },
      { year: 2022, count: 19 },
      { year: 2023, count: 3 },
      { year: 2024, count: 8 },
      { year: 2025, count: 4 }
    ]
  };

  get filteredPublications() {
    if (!this.selectedCategory) {
      return this.publications;
    }

    return this.publications.filter(pub => {
      if (this.selectedCategory === 'Hydrological Modeling') {
        return pub.abstract.toLowerCase().includes('hydrological') || pub.abstract.toLowerCase().includes('wetspa');
      } else if (this.selectedCategory === 'Uncertainty Analysis') {
        return pub.abstract.toLowerCase().includes('model optimization') || pub.abstract.toLowerCase().includes('confidence');
      } else if (this.selectedCategory === 'Data Science') {
        return pub.abstract.toLowerCase().includes('data') && pub.abstract.toLowerCase().includes('database');
      } else if (this.selectedCategory === 'Remote Sensing') {
        return pub.abstract.toLowerCase().includes('nexrad') || pub.abstract.toLowerCase().includes('satellite');
      } else if (this.selectedCategory === 'Algorithmic Approaches') {
        return pub.abstract.toLowerCase().includes('calibration') || pub.abstract.toLowerCase().includes('algorithmic');
      }
      return true;
    });
  }

  setCategory(category: string | null) {
    this.selectedCategory = category;
  }

  // Get the maximum citation count for scaling the Y-axis
  getMaxCitationCount(): number {
    if (!this.citationStats || !this.citationStats.yearlyStats || this.citationStats.yearlyStats.length === 0) {
      return 30; // Default value if no data
    }
    
    // Find the maximum count in the yearly stats
    return Math.max(...this.citationStats.yearlyStats.map(stat => stat.count));
  }
  
  // Make Math available to the template
  Math = Math;
}
