welcome:
  description: Welcome posts introducing new features or sections
  permalink: /tags/welcome-tag

asafarim:
  description: Posts related to the ASafariM project
  permalink: /tags/asafarim-tag

blog:
  description: Meta posts about the blog itself
  permalink: /tags/blog-tag

automation:
  description: Posts about automation and automated processes
  permalink: /tags/automation-tag

technology:
  description: Posts related to technology trends and innovations
  permalink: /tags/technology-tag

data-management:
  description: Posts about data management and database systems
  permalink: /tags/data-management-tag

xitechnix:
  description: Posts related to XiTechniX projects and technologies
  permalink: /tags/xitechnix-tag

programming:
  description: Posts about programming languages, techniques, and best practices
  permalink: /tags/programming-tag

angular:
  description: Posts about Angular development
  permalink: /tags/angular-tag

clean-architecture:
  description: Posts about Clean Architecture principles
  permalink: /tags/clean-architecture-tag

dotnet:
  description: Posts about .NET development
  permalink: /tags/dotnet-tag

fullstack:
  description: Posts about fullstack development
  permalink: /tags/fullstack-tag

windsurf:
  description: Windsurf AI integration code editor
  permalink: /tags/windsurf-tag

ai:
  description: Posts about AI and machine learning
  permalink: /tags/ai-tag

machine-learning:
  description: Posts about machine learning and AI
  permalink: /tags/machine-learning-tag

codeium:
  description: Posts about Codeium
  permalink: /tags/codeium-tag

debugging:
  description: Posts about debugging
  permalink: /tags/debugging-tag

docker:
  description: Posts about Docker
  permalink: /tags/docker-tag

efficiency:
  description: Posts about efficiency and productivity
  permalink: /tags/efficiency-tag

productivity:
  description: Posts about productivity and workflow optimization
  permalink: /tags/productivity-tag

troubleshooting:
  description: Posts about troubleshooting and problem-solving
  permalink: /tags/troubleshooting-tag

react:
  description: Posts about React.js development
  permalink: /tags/react-tag

portfolio:
  description: Posts about portfolio development and projects
  permalink: /tags/portfolio-tag

multi-user:
  description: Posts about multi-user systems and authentication
  permalink: /tags/multi-user-tag

api:
  description: Posts about API development and design
  permalink: /tags/api-tag

open-source:
  description: Posts about open source development
  permalink: /tags/open-source-tag